name: csvue
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<2.0.0
  - pandas>=2.1.4
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - plotly>=5.18.0
  - pillow>=10.2.0
  - polars>=0.20.7
  - duckdb>=0.10.0
  - scikit-learn>=1.4.0
  - pyyaml>=6.0.1
  - pyarrow>=14.0.1
  - fastparquet>=2023.10.1
  - pip
  - pip:
    - ttkbootstrap>=1.10.1
    - pywebview>=5.0.2
    - pandastable>=0.13.1
    - pyreadr>=0.4.9 